name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install

      - name: lint
        run: |
          shopt -s expand_aliases
          . ./envr.ps1
          lint
